formulario_indexf:
    path:     /form/indexf
    defaults: { _controller: FormularioBundle:Form:indexf }

formulario_addf:
    path:   /form/addf
    defaults: { _controller: FormularioBundle:Form:addf }

formulario_editf:
    path:   /form/editf
    defaults: { _controller: FormularioBundle:Form:editf }

formulario_viewf: 
    path:     /form/viewf
    defaults: {_controller: FormularioBundle:Form:viewf}

formulario_deletef:
    path:     /form/deletef
    defaults: {_controller: FormularioBundle:Form:deletef}

#TABLAS

formulario_tablas:
    path:     /form/tablas
    defaults: { _controller: FormularioBundle:Form:tablas }

formulario_tablaMezcla:
    path:     /form/tmezcla
    defaults: { _controller: FormularioBundle:Form:tablaMezclas }

formulario_tablaFacturacion:
    path:     /form/tfacturacion
    defaults: { _controller: FormularioBundle:Form:tablaFacturacion }

formulario_tablaLugares:
    path:     /form/tlugares
    defaults: { _controller: FormularioBundle:Form:tablaLugares }

formulario_tablaServicios:
    path:     /form/tservicios
    defaults: { _controller: FormularioBundle:Form:tablaServicios }

formulario_tablaServiciosSolicitados:
    path:     /form/tservsolicitados
    defaults: { _controller: FormularioBundle:Form:tablaServiciosSolicitados }

formulario_tablaSolicitante:
    path:     /form/tsolicitante
    defaults: { _controller: FormularioBundle:Form:tablaSolicitante }

formulario_tablaSolicitudes:
    path:     /form/tsolicitudes
    defaults: { _controller: FormularioBundle:Form:tablaSolicitudes }

#EJEMPLOS

formulario_ejemplo:
    path:     /form/ejemplo/{page}
    defaults: { _controller: FormularioBundle:Form:ejemplo, page: 0 }
    requirements:

formulario_ejemplo2:
    path:     /form/ejemplo2
    defaults: { _controller: FormularioBundle:Form:ejemplo2}
    requirements:

####page: \d+