audiovisuales_homepage:
    path:     /audiovisuales/
    defaults: { _controller: AudiovisualesBundle:Default:index }

audiovisuales_solicitud_nueva:
    path:     /audiovisuales/solicitudes/nueva
    defaults: { _controller: AudiovisualesBundle:Audiovisuales:nueva }

audiovisuales_error:
    path:     /audiovisuales/solicitudes/error
    defaults: { _controller: AudiovisualesBundle:Audiovisuales:error }

audiovisuales_done:
    path:     /audiovisuales/solicitudes/done
    defaults: { _controller: AudiovisualesBundle:Audiovisuales:done }

