audiovisuales_homepage:
    path:     /audiovisuales/
    defaults: { _controller: AudiovisualesBundle:Default:index }

audiovisuales_solicitud_nueva:
    path:     /audiovisuales/solicitudes/nueva
    defaults: { _controller: AudiovisualesBundle:Audiovisuales:nueva }
